package haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type HaproxyJob struct {

	/*HaProxy - Descr: DNS Hold time Default: 10s
*/
	HaProxy *HaProxy `yaml:"ha_proxy,omitempty"`

}